### ISSUE TITLE
Arduino IDE 2.x RuntimeError: Click will abort

### ISSUE THREAD

**Issue by tamberg** [tamberg/mse-tsm-mobcom#16]
Installed nRF52 board package, compiling _blink_ fails with:

```
Traceback (most recent call last):
  File "__main__.py", line 317, in <module>
  File "click/core.py", line 1134, in __call__
  File "click/core.py", line 1040, in main
  File "click/_unicodefun.py", line 100, in _verify_python_env
RuntimeError: Click will abort further execution because Python was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/unicode-support/ for mitigation steps.

This system lists some UTF-8 supporting locales that you can pick from. The following suitable locales were discovered: af_ZA.UTF-8, am_ET.UTF-8, be_BY.UTF-8, bg_BG.UTF-8, ca_ES.UTF-8, cs_CZ.UTF-8, da_DK.UTF-8, de_AT.UTF-8, de_CH.UTF-8, de_DE.UTF-8, el_GR.UTF-8, en_AU.UTF-8, en_CA.UTF-8, en_GB.UTF-8, en_IE.UTF-8, en_NZ.UTF-8, en_US.UTF-8, es_ES.UTF-8, et_EE.UTF-8, eu_ES.UTF-8, fi_FI.UTF-8, fr_BE.UTF-8, fr_CA.UTF-8, fr_CH.UTF-8, fr_FR.UTF-8, he_IL.UTF-8, hr_HR.UTF-8, hu_HU.UTF-8, hy_AM.UTF-8, is_IS.UTF-8, it_CH.UTF-8, it_IT.UTF-8, ja_JP.UTF-8, kk_KZ.UTF-8, ko_KR.UTF-8, lt_LT.UTF-8, nl_BE.UTF-8, nl_NL.UTF-8, no_NO.UTF-8, pl_PL.UTF-8, pt_BR.UTF-8, pt_PT.UTF-8, ro_RO.UTF-8, ru_RU.UTF-8, sk_SK.UTF-8, sl_SI.UTF-8, sr_YU.UTF-8, sv_SE.UTF-8, tr_TR.UTF-8, uk_UA.UTF-8, zh_CN.UTF-8, zh_HK.UTF-8, zh_TW.UTF-8
[21608] Failed to execute script __main__

exit status 1

Compilation error: exit status 1
```

**Comment by tamberg** [comment]
Found https://github.com/arduino/arduino-ide/issues/1513

**Comment by tamberg** [comment]
Install _adafruit-nrfutil_ with
```
$ pip3 install --user adafruit-nrfutil
```

Replace board package specific, pre-built _adafruit-nrfutil_ binary with the above binary:
```
$ mv /Users/tamberg/Library/Arduino15/packages/adafruit/hardware/nrf52/1.6.1/tools/adafruit-nrfutil/macos/adafruit-nrfutil /Users/tamberg/Library/Arduino15/packages/adafruit/hardware/nrf52/1.6.1/tools/adafruit-nrfutil/macos/adafruit-nrfutil.bak
$ cp /Users/tamberg/Library/Python/3.9/bin/adafruit-nrfutil /Users/tamberg/Library/Arduino15/packages/adafruit/hardware/nrf52/1.6.1/tools/adafruit-nrfutil/macos/
$ ls /Users/tamberg/Library/Arduino15/packages/adafruit/hardware/nrf52/1.6.1/tools/adafruit-nrfutil/macos/
adafruit-nrfutil  adafruit-nrfutil.bak
```

User name and version numbers might vary.

Seems to fix the issue in Arduino IDE.

**Comment by tamberg** [comment]
P.S. Your install path might be different, consider using _which adafruit-nrfutil_ or _pip uninstall adafruit-nrfutil_ to find it.
